### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by pwannenmacher** [Frachtwerk/essencium-backend#14]
- Create documentation for external pages. 
- Framework: Nextra
- Style: see https://github.com/Frachtwerk/essencium-frontend

to be published on https://docs.essencium.dev/backend

**Comment by pwannenmacher** [comment]
# Even add explanation how to expose application metrics

Spring actuator brings metrics (e.g. request timing, JVM threads, heap, etc.) more or less out of the box. Investigate how this might be useful for us.
        
- https://docs.spring.io/spring-metrics/docs/current/public/prometheus
- https://tomgregory.com/spring-boot-default-metrics/

**Comment by hoelger-frachtwerk** [comment]
In the root readme almost ALL  hyperlinks "see here" are broken (only postman works)
