### ISSUE TITLE
Getting a 500 if JWT is expired

### ISSUE THREAD

**Issue by qhantom** [Frachtwerk/essencium-backend#202]
**Describe the bug**
If the header contains an expired JWT a `500` status code is sent. I'd suggest to respond with a `401` in order to handle it properly in frontends (i.e. redirecting to login page).

**Expected behavior**
A 401 is received as response status code.

**Comment by pwannenmacher** [comment]
Hmm, with an expired session token it looks like this...

```json
{
    "timestamp": "2023-12-15T11:32:28.857+00:00",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/v1/example"
}
```

**Comment by pwannenmacher** [comment]
If no refresh token exists as a cookie, this is what you get:

```json
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "Required cookie 'refreshToken' is not present.",
    "instance": "/auth/renew"
}
```

**Comment by pwannenmacher** [comment]
This message appears when the refresh token has expired:

```json
{
    "timestamp": "2023-12-15T11:37:48.737+00:00",
    "status": 401,
    "error": "Unauthorized",
    "message": "Session token not found. Session expired?",
    "path": "/auth/renew"
}
```

**Comment by qhantom** [comment]
Thanks! The ESS frontend redirect ist now working properly again 🙂
