### ISSUE TITLE
AbstractUserController does not inherit from AbstractAccessAwareController

### ISSUE THREAD

**Issue by hoelger-frachtwerk** [Frachtwerk/essencium-backend#388]
**Is your feature request related to a problem? Please describe.**
Some functionalities have to be implemented twice, because the AbstractUserController does not inherit from AbstractAccessAwareController. When implementing access to "owned" entities, this requires specifications in the method signatures. 

**Describe the solution you'd like**
AbstractUserController (and the RoleController) should inherit from AbstractAccessAwareController. 

**Describe alternatives you've considered**
The outcome might be to not implement this, then it should be documented why. There might be some useful discussions about this in the old Gitlab repo.

**additional context**
"Nicht ID als Long sondern als Teil der Specification" is part of my notes but I would have to get more into the code, to understand what paul wanted to say with this.

**Comment by cholakov11** [comment]
Reason for reopening: Annotatitions should be adjusted to not cause a ConstraintDeclarationException.
