### ISSUE TITLE
Modify Email Filter at User to Accept Partial Entries

### ISSUE THREAD

**Issue by DuciDuc03** [Frachtwerk/essencium-backend#576]
**Is your feature request related to a problem? Please describe.**
The current email filter at the user requires the full email address for filtering. We propose modifying this filter to allow partial entries and individual characters

**Describe the solution you'd like**
Modify the email filter logic at the user endpoint to accept partial entries and individual characters. This change will allow to filter and search for users based on incomplete email addresses.

**Comment by JelmenGuhlke** [comment]
Closed with https://github.com/Frachtwerk/essencium-backend/pull/579
